config {
  type: "operations",
  tags: ["external"],
  hasOutput: true
}

CREATE OR REPLACE EXTERNAL TABLE ${self()} (

Nivaa3 STRING
,Nivaa3_T STRING
,aar STRING
,Pris STRING

)
OPTIONS (
  format = "CSV",
  uris = ["gs://raw-hist-dev-datapuls-cloud/reference/hr_Vikarbyra_Timespris_Datapuls.csv"],
  field_delimiter = ";",
  ignore_unknown_values = true,
  allow_quoted_newlines = true,
  allow_jagged_rows = true,
  skip_leading_rows = 1, --first row as header
  quote = '"'
);